# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c623b1a10d5dac7c293691dc1f80b672"
name = "AdFeed AI"
application_url = "https://deltfu.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/app_subscriptions_update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/app_uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/products_delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/products_update"
  topics = [ "products/update" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_legal_policies,read_products,write_products"

[auth]
redirect_urls = [
  "https://deltfu.com/auth/callback",
  "https://deltfu.com/api/shopify/callback"
]

[sidekick]
extensions_summary = "Generate Google Shopping feeds from the Shopify catalog"
